// Curated research-area labels. Each conference profile is grounded in its
// linked organizer page; some links describe a previous edition when the next
// CFP is not yet available. These labels are for discovery, not acceptance advice.
export const topicCatalog = [
  { id: "ai", label: "人工智能", aliases: ["人工智能", "AI", "artificial intelligence"] },
  { id: "nlp", label: "自然语言处理", aliases: ["自然语言处理", "计算语言学", "NLP", "natural language processing", "computational linguistics"] },
  { id: "llm", label: "大语言模型", aliases: ["大语言模型", "大模型", "语言模型", "LLM", "large language model", "language model", "生成式 AI", "生成式人工智能"] },
  { id: "rag", label: "检索与 RAG", aliases: ["检索增强生成", "检索增强", "RAG", "信息检索", "retrieval augmented generation", "information retrieval"] },
  { id: "agents", label: "智能体", aliases: ["智能体", "AI agent", "agentic AI", "agentic", "agents", "agent"] },
  { id: "ml", label: "机器学习", aliases: ["机器学习", "深度学习", "表征学习", "ML", "machine learning", "deep learning", "representation learning"] },
  { id: "vision", label: "计算机视觉", aliases: ["计算机视觉", "多模态视觉", "图像理解", "视觉", "CV", "computer vision", "vision"] },
  { id: "multimodal", label: "多模态与跨模态", aliases: ["多模态", "多模态大模型", "视觉语言模型", "视觉语言", "VLM", "multimodal", "vision language model", "vision-language model", "跨模态", "cross-modal"] },
  { id: "music", label: "音乐信息处理", aliases: ["音乐", "音乐信息检索", "音乐信息处理", "MIR", "music", "music information retrieval", "music AI"] },
  { id: "music-llm", label: "音乐与大模型", aliases: ["音乐大模型", "音乐与大模型", "音乐和大模型", "音乐与大语言模型", "音乐和大语言模型", "音乐 大模型", "音乐 LLM", "音乐语言模型", "音乐基础模型", "music LLM", "music language model", "music foundation model"] },
  { id: "music-generation", label: "音乐生成与创作", aliases: ["音乐生成", "音乐创作", "自动作曲", "音乐合成", "文生音乐", "text-to-music", "music generation", "music synthesis", "automatic composition"] },
  { id: "music-understanding", label: "音乐理解与检索", aliases: ["音乐理解", "音乐检索", "音乐推荐", "音乐问答", "音乐描述", "music understanding", "music retrieval", "music recommendation", "music captioning", "music question answering"] },
  { id: "audio", label: "音频处理", aliases: ["音频", "声音", "声学", "audio", "acoustic", "sound processing"] },
  { id: "audio-language", label: "音频语言模型", aliases: ["音频语言模型", "音频大模型", "音频文本模型", "音频文本", "audio language model", "audio-language model", "audio LLM", "audio-text model"] },
  { id: "speech", label: "语音与歌声", aliases: ["语音", "歌声", "歌声合成", "singing voice", "speech", "voice synthesis", "speech processing"] },
  { id: "ml-systems", label: "AI 系统与模型推理", aliases: ["AI Infra", "AI 基础设施", "人工智能基础设施", "AI系统", "AI 系统", "机器学习系统", "大模型系统", "训练系统", "推理服务", "模型推理", "大模型推理", "推理系统", "ML systems", "inference serving", "model serving"] },
  { id: "systems", label: "计算机系统", aliases: ["计算机系统", "系统研究", "系统", "computer systems", "systems research"] },
  { id: "distributed", label: "分布式与云系统", aliases: ["分布式系统", "分布式", "云计算", "云系统", "数据中心", "distributed systems", "cloud computing", "data center", "datacenter"] },
  { id: "os", label: "操作系统", aliases: ["操作系统", "系统软件", "内核", "虚拟化", "operating systems", "OS", "kernel", "virtualization"] },
  { id: "storage", label: "存储与文件系统", aliases: ["文件系统", "存储系统", "存储", "storage", "file systems", "filesystem"] },
  { id: "networking", label: "网络系统", aliases: ["网络系统", "计算机网络", "数据通信", "通信网络", "网络", "network", "networking", "network systems", "computer networks"] },
  { id: "architecture", label: "计算机体系结构", aliases: ["计算机体系结构", "计算机架构", "微体系结构", "微架构", "体系结构", "处理器", "computer architecture", "microarchitecture", "processor"] },
  { id: "hpc", label: "高性能计算", aliases: ["高性能计算", "超级计算", "HPC", "high performance computing", "supercomputing"] },
  { id: "parallel", label: "并行计算", aliases: ["并行计算", "并行编程", "并行与分布式", "parallel computing", "parallel programming"] },
  { id: "accelerators", label: "加速器与 AI 硬件", aliases: ["AI 加速器", "加速器", "AI 硬件", "专用硬件", "GPU", "hardware accelerator", "accelerators"] },
  { id: "hardware", label: "硬件与芯片", aliases: ["硬件", "芯片", "hardware", "chip", "semiconductor"] },
  { id: "eda", label: "EDA 与芯片设计", aliases: ["EDA", "电子设计自动化", "设计自动化", "芯片设计", "电路设计", "electronic design automation", "chip design"] },
  { id: "ai-eda", label: "AI 辅助 EDA", aliases: ["AI for EDA", "AI 辅助 EDA", "机器学习辅助芯片设计", "智能芯片设计", "ML for EDA"] },
  { id: "physical-design", label: "物理设计", aliases: ["物理设计", "布局布线", "placement", "routing", "physical design"] },
  { id: "synthesis", label: "逻辑综合", aliases: ["逻辑综合", "高层次综合", "HLS", "logic synthesis", "high-level synthesis"] },
  { id: "hardware-verification", label: "硬件验证", aliases: ["硬件验证", "电路验证", "hardware verification", "circuit verification"] },
  { id: "formal", label: "形式化验证", aliases: ["形式化验证", "形式化方法", "形式化", "软件验证", "formal verification", "formal methods", "program verification"] },
  { id: "model-checking", label: "模型检测", aliases: ["模型检测", "model checking", "SAT", "SMT"] },
  { id: "proof-assistants", label: "定理证明与证明助手", aliases: ["定理证明", "证明助手", "交互式证明", "Lean", "Coq", "Rocq", "Isabelle", "theorem proving", "proof assistant"] },
  { id: "pl", label: "程序语言", aliases: ["程序语言", "编程语言", "类型系统", "程序语义", "PL", "programming languages", "type systems", "semantics"] },
  { id: "compilers", label: "编译器与程序分析", aliases: ["编译器", "编译优化", "程序分析", "compilers", "compiler", "program analysis"] },
  { id: "software-engineering", label: "软件工程", aliases: ["软件工程", "软件质量", "软件测试", "software engineering", "software testing"] },
  { id: "logic", label: "计算逻辑", aliases: ["计算逻辑", "数理逻辑", "计算理论", "logic in computer science", "computational logic"] },
];

// topicIds are central research areas; relatedTopicIds are CFP-supported
// adjacent areas and intentionally rank below a conference's core topics.
export const conferenceProfiles = {
  acl: { summary: "语言技术与计算语言学的综合研究，投稿流程经 ACL Rolling Review 与会议承诺。", topicIds: ["nlp", "llm"], relatedTopicIds: ["ai", "rag", "agents", "multimodal"] },
  emnlp: { summary: "自然语言处理的实证研究，涵盖语言模型、任务、评测与应用。", topicIds: ["nlp", "llm"], relatedTopicIds: ["ai", "rag", "agents", "multimodal"] },
  naacl: { summary: "自然语言处理与计算语言学研究，主会采用 ARR 投稿及会议承诺。", topicIds: ["nlp", "llm"], relatedTopicIds: ["ai", "rag", "agents", "multimodal"] },
  neurips: { summary: "机器学习方法、模型及应用的综合会议，2026 征稿含面向创作者的 AI；音乐工作需有可推广的模型或方法贡献。", topicIds: ["ml"], relatedTopicIds: ["ai", "llm", "vision", "multimodal", "ml-systems", "music-llm", "music-generation"] },
  iclr: { summary: "表征学习与深度学习研究，覆盖模型方法及相关应用。", topicIds: ["ml"], relatedTopicIds: ["ai", "vision", "multimodal", "nlp"] },
  icml: { summary: "机器学习算法、理论与应用，并涵盖机器学习系统研究。", topicIds: ["ml"], relatedTopicIds: ["ai", "ml-systems", "llm"] },
  aaai: { summary: "人工智能综合研究，包含学习方法、语言、视觉及智能体等方向。", topicIds: ["ai", "ml"], relatedTopicIds: ["nlp", "vision", "agents", "llm", "multimodal"] },
  ijcai: { summary: "人工智能综合研究，覆盖学习、推理及多类 AI 应用。", topicIds: ["ai", "ml"], relatedTopicIds: ["nlp", "vision", "agents", "multimodal"] },
  coling: { summary: "计算语言学与自然语言处理研究，主会采用 ARR 流程。", topicIds: ["nlp", "llm"], relatedTopicIds: ["ai", "rag", "agents", "multimodal"] },
  cvpr: { summary: "计算机视觉与模式识别研究，涵盖图像、视频及多模态视觉。", topicIds: ["vision", "multimodal"], relatedTopicIds: ["ai", "ml", "agents"] },
  iccv: { summary: "计算机视觉与图像理解的综合研究会议。", topicIds: ["vision", "multimodal"], relatedTopicIds: ["ai", "ml"] },

  mlsys: { summary: "机器学习与系统交叉，涵盖训练、推理服务、分布式方案和专用硬件。", topicIds: ["ml-systems", "llm"], relatedTopicIds: ["ai", "systems", "ml", "distributed", "accelerators", "hardware", "multimodal", "compilers", "agents"] },
  asplos: { summary: "体系结构、操作系统与程序语言交叉的系统研究。", topicIds: ["architecture", "os", "pl"], relatedTopicIds: ["systems", "distributed", "storage", "accelerators", "hardware", "ml-systems", "compilers"] },
  isca: { summary: "计算机体系结构研究，涵盖处理器、存储层次及专用加速。", topicIds: ["architecture", "hardware"], relatedTopicIds: ["accelerators", "storage"] },
  micro: { summary: "微体系结构与处理器设计，涉及软硬件接口和编译优化。", topicIds: ["architecture", "hardware"], relatedTopicIds: ["accelerators", "compilers"] },
  hpca: { summary: "高性能计算机体系结构，涵盖加速器与大规模计算平台。", topicIds: ["architecture", "hardware"], relatedTopicIds: ["accelerators", "distributed"] },
  dac: { summary: "电子设计自动化与芯片设计，涵盖物理设计、综合和验证。", topicIds: ["eda", "ai-eda", "physical-design", "synthesis", "hardware"], relatedTopicIds: ["hardware-verification", "formal", "accelerators", "ml-systems"] },
  iccad: { summary: "计算机辅助设计与 EDA，涵盖电路设计、综合、布局布线和验证。", topicIds: ["eda", "ai-eda", "physical-design", "synthesis", "hardware"], relatedTopicIds: ["hardware-verification", "formal", "accelerators"] },
  date: { summary: "设计自动化、测试与嵌入式系统，主会和特别轨的投稿节点分别列出。", topicIds: ["eda", "ai-eda", "hardware-verification", "hardware"], relatedTopicIds: ["synthesis", "accelerators", "formal"] },
  "aspdac": { summary: "电子设计自动化与芯片设计研究，覆盖设计方法、工具和验证。", topicIds: ["eda", "ai-eda", "hardware"], relatedTopicIds: ["synthesis", "accelerators", "hardware-verification", "formal"] },

  osdi: { summary: "操作系统与系统软件设计和实现，涵盖分布式、存储、云和可靠性。", topicIds: ["systems", "os", "distributed"], relatedTopicIds: ["storage", "networking", "ml-systems"] },
  sosp: { summary: "操作系统原理与系统研究，关注系统设计、实现及影响。", topicIds: ["systems", "os", "distributed"], relatedTopicIds: ["storage", "networking", "ml-systems"] },
  eurosys: { summary: "计算机系统研究，覆盖操作系统、云、存储及系统分析。", topicIds: ["systems", "os", "distributed"], relatedTopicIds: ["storage", "networking", "ml-systems", "formal"] },
  "usenix-atc": { summary: "历史性的系统研究综合会议；主办方已宣布在 2025 年后结束举办。", topicIds: ["systems", "os", "distributed"], relatedTopicIds: ["storage", "networking"] },
  "sigops-atc": { summary: "ACM SIGOPS 的系统研究综合会议，涵盖操作系统与系统软件。", topicIds: ["systems", "os", "distributed"], relatedTopicIds: ["storage", "networking", "ml-systems"] },
  fast: { summary: "文件与存储系统的设计、实现、性能与可靠性。", topicIds: ["storage"], relatedTopicIds: ["systems", "distributed", "formal"] },
  nsdi: { summary: "网络化系统的设计与实现，涉及网络、分布式系统和云平台。", topicIds: ["networking", "distributed"], relatedTopicIds: ["systems", "storage", "ml-systems", "formal"] },
  sigcomm: { summary: "数据通信与计算机网络研究，涵盖网络机制和系统。", topicIds: ["networking"], relatedTopicIds: ["systems", "distributed"] },

  cav: { summary: "计算机辅助形式化验证，包括模型检测、证明工具及软硬件验证。", topicIds: ["formal", "model-checking"], relatedTopicIds: ["proof-assistants", "hardware-verification"] },
  popl: { summary: "程序语言原理、语义、类型系统与形式化基础。", topicIds: ["pl", "logic"], relatedTopicIds: ["formal", "compilers"] },
  pldi: { summary: "程序语言设计与实现，涵盖编译器和程序分析；细分方向以正式 CFP 为准。", topicIds: ["pl", "compilers"], relatedTopicIds: ["formal"] },
  lics: { summary: "计算机科学中的逻辑与形式化基础，涵盖语义和模型检测。", topicIds: ["logic"], relatedTopicIds: ["formal", "model-checking", "pl"] },
  cpp: { summary: "证明助手、机器化证明与可信程序，包括认证编译和系统。", topicIds: ["proof-assistants", "formal"], relatedTopicIds: ["logic", "compilers", "pl"] },
  tacas: { summary: "系统构建与分析的验证工具和算法，涵盖模型检测等技术。", topicIds: ["formal", "model-checking"], relatedTopicIds: ["compilers"] },
  fm: { summary: "形式化方法的理论、工具与应用，包括系统及软件验证。", topicIds: ["formal"], relatedTopicIds: ["model-checking", "proof-assistants"] },

  aistats: { summary: "人工智能、机器学习与统计学交叉的算法、理论和应用。", topicIds: ["ml"], relatedTopicIds: ["ai", "llm", "vision"] },
  eacl: { summary: "欧洲计算语言学主会，经 ARR 评审后向会议承诺。", topicIds: ["nlp", "llm"], relatedTopicIds: ["ai", "rag", "agents", "multimodal"] },
  colm: { summary: "语言模型的训练、能力与评测；2026 征稿明确含音频及多模态语言模型，音乐工作需体现语言模型贡献。", topicIds: ["llm"], relatedTopicIds: ["nlp", "ml", "rag", "agents", "ml-systems", "music-llm", "audio-language"] },
  eccv: { summary: "计算机视觉与模式识别综合研究，含视觉语言和多模态方向。", topicIds: ["vision", "multimodal"], relatedTopicIds: ["ai", "ml", "agents"] },
  aamas: { summary: "自主智能体与多智能体系统；生成式 AI 稿件需有核心智能体贡献。", topicIds: ["agents"], relatedTopicIds: ["ai", "ml", "llm"] },
  sigir: { summary: "信息检索与搜索，涵盖检索增强生成和 Agentic IR。", topicIds: ["rag"], relatedTopicIds: ["nlp", "llm", "agents", "ml", "music-understanding"] },

  socc: { summary: "云计算系统的设计与实践，涉及分布式平台和数据中心。", topicIds: ["distributed", "systems"], relatedTopicIds: ["ml-systems", "storage", "networking"] },
  ipdps: { summary: "并行与分布式处理，涵盖高性能计算和大规模系统。", topicIds: ["parallel", "distributed", "hpc"], relatedTopicIds: ["systems", "architecture", "accelerators"] },
  ppopp: { summary: "并行程序设计的原理与实现，包括编译器、运行时和硬件接口。", topicIds: ["parallel"], relatedTopicIds: ["pl", "compilers", "systems", "accelerators", "hpc"] },
  sc: { summary: "高性能计算、网络、存储与分析的综合会议。", topicIds: ["hpc"], relatedTopicIds: ["parallel", "distributed", "networking", "storage", "architecture", "ml-systems"] },
  fpga: { summary: "可重构计算与空间架构，包括 FPGA、CGRA 和 AI 加速硬件。", topicIds: ["accelerators", "hardware", "architecture"], relatedTopicIds: ["eda", "ml-systems", "synthesis"] },
  "sca-hpcasia": { summary: "亚太地区高性能计算研究，涉及并行系统、应用和加速架构。", topicIds: ["hpc"], relatedTopicIds: ["parallel", "distributed", "accelerators", "architecture"] },

  fse: { summary: "软件工程研究，包括程序分析、测试、开发过程和系统可靠性。", topicIds: ["software-engineering"], relatedTopicIds: ["compilers", "formal", "model-checking", "pl"] },
  esop: { summary: "程序语言与程序系统的规范、设计、分析和实现。", topicIds: ["pl"], relatedTopicIds: ["formal", "compilers", "logic", "software-engineering"] },
  fossacs: { summary: "软件科学和计算结构的理论基础，涵盖逻辑、语义与程序验证。", topicIds: ["logic", "pl"], relatedTopicIds: ["formal", "model-checking", "software-engineering"] },
  ifs: { summary: "以形式化方法和基础理论支持可靠的软件及系统工程。", topicIds: ["formal", "software-engineering"], relatedTopicIds: ["model-checking", "systems", "pl"] },
  ispd: { summary: "芯片物理设计，包括布局布线、时序优化和相关设计方法。", topicIds: ["physical-design", "eda"], relatedTopicIds: ["ai-eda", "hardware", "synthesis"] },
  mlcad: { summary: "机器学习与 CAD／EDA 交叉，聚焦智能设计方法和工具。", topicIds: ["ai-eda", "eda"], relatedTopicIds: ["ml", "physical-design", "hardware"] },
  vmcai: { summary: "程序验证、模型检测与抽象解释，兼及静态分析和推导技术。", topicIds: ["formal", "model-checking"], relatedTopicIds: ["pl", "compilers", "logic"] },
  oopsla: { summary: "编程语言、程序系统及应用，包含语言实现、语义、分析与验证。", topicIds: ["pl"], relatedTopicIds: ["compilers", "formal", "systems"] },
  fmcad: { summary: "硬件与计算系统的形式化设计和验证，涵盖模型检测与综合。", topicIds: ["formal", "hardware-verification", "model-checking"], relatedTopicIds: ["eda", "synthesis", "hardware"] },
  itp: { summary: "交互式定理证明、证明助手及其在软硬件验证与数学中的应用。", topicIds: ["proof-assistants", "formal"], relatedTopicIds: ["logic", "hardware-verification"] },
  cgo: { summary: "代码生成和程序优化研究，涉及编译器实现、分析与体系结构。", topicIds: ["compilers"], relatedTopicIds: ["pl", "architecture", "systems"] },

  ismir: { summary: "音乐信息检索与计算音乐研究，覆盖音乐理解、生成、评价及多模态音乐系统。", topicIds: ["music", "music-llm", "music-generation", "music-understanding"], relatedTopicIds: ["audio", "audio-language", "speech", "multimodal", "nlp"] },
  aimc: { summary: "AI 与音乐创作的技术及实践研究，涵盖生成模型、人机共创与评价。", topicIds: ["music", "music-llm", "music-generation"], relatedTopicIds: ["audio", "multimodal", "agents"] },
  icmc: { summary: "计算机音乐、声音艺术与创作技术，包含 AI／机器学习在音乐中的应用。", topicIds: ["music", "music-generation"], relatedTopicIds: ["music-llm", "audio", "speech"] },
  smc: { summary: "声音与音乐计算的跨学科研究，覆盖分析、合成、创作及交互。", topicIds: ["music", "audio"], relatedTopicIds: ["music-llm", "music-generation", "music-understanding", "speech"] },
  nime: { summary: "音乐表达的新型交互界面；生成模型研究需体现演奏、控制或人机交互贡献。", topicIds: ["music"], relatedTopicIds: ["music-generation", "audio"] },
  dafx: { summary: "数字音频效果、声音合成与处理；机器学习工作需聚焦音频方法。", topicIds: ["audio"], relatedTopicIds: ["music", "music-generation", "music-understanding"] },
  icassp: { summary: "音频、声学、语音与信号处理研究，含生成式 AI 及多模态方法。", topicIds: ["audio", "audio-language", "speech"], relatedTopicIds: ["music", "music-llm", "music-generation", "music-understanding", "multimodal", "ml"] },
  acmmm: { summary: "多媒体内容理解与生成；音乐论文需有音频或跨模态方法贡献。", topicIds: ["multimodal"], relatedTopicIds: ["music", "music-llm", "music-generation", "music-understanding", "audio", "audio-language"] },
  icmr: { summary: "多媒体搜索、检索和推荐，适合音乐检索及音乐与文本的跨模态检索。", topicIds: ["rag"], relatedTopicIds: ["music", "music-understanding", "audio", "multimodal"] },
  mmsys: { summary: "多媒体系统研究，2027 征稿含多模态大模型；音乐工作需有部署、传输或系统性能贡献。", topicIds: ["systems", "multimodal"], relatedTopicIds: ["music-llm", "audio", "audio-language", "ml-systems"] },
  interspeech: { summary: "语音与口语技术研究；音乐相关工作主要涉及歌声和语音音频交叉。", topicIds: ["speech", "audio-language"], relatedTopicIds: ["audio"] },
};
